# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170513_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
