# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170513_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number_of_comments',
            field=models.IntegerField(null=True),
        ),
    ]
