# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20170514_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
