# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
