# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20170514_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='lowercase_name',
            field=models.CharField(default='YOU_SHOULD_RESET_THE_DATABASE', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.Tag'),
        ),
    ]
