# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hn_id', models.IntegerField()),
                ('article_url', models.URLField(max_length=255)),
                ('score', models.IntegerField()),
                ('number_of_comments', models.IntegerField()),
            ],
        ),
    ]
