# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='hn_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
