# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170513_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='age',
            new_name='timestamp',
        ),
    ]
